# Generated by Django 6.0.2 on 2026-02-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("floor", models.IntegerField()),
                ("building", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("room", "Room"), ("connector", "Connector")],
                        max_length=24,
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        blank=True,
                        choices=[("stairs", "Stairs"), ("elevator", "Elevator")],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "ordering": ("building", "floor", "name"),
            },
        ),
        migrations.CreateModel(
            name="NodeEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("walk", "Walk"),
                            ("stairs", "Stairs"),
                            ("elevator", "Elevator"),
                        ],
                        default="walk",
                        max_length=24,
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_node_edges",
                        to="navigation.node",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_node_edges",
                        to="navigation.node",
                    ),
                ),
            ],
            options={
                "ordering": ("from_node_id", "to_node_id"),
                "unique_together": {("from_node", "to_node")},
            },
        ),
    ]
