# Generated by Django 6.0.1 on 2026-02-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_node_nodeedge"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="NavigationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preference_mode", models.CharField(default="default", max_length=32)),
                ("route_node_count", models.PositiveIntegerField(default=0)),
                ("route_distance", models.FloatField(default=0)),
                ("duration_seconds", models.FloatField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("route_node_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["building"], name="navigation__buildin_da2648_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["floor"], name="navigation__floor_b1bd3e_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["building", "floor"], name="navigation__buildin_96c9ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeedge",
            index=models.Index(
                fields=["from_node"], name="navigation__from_no_4b715b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeedge",
            index=models.Index(
                fields=["to_node"], name="navigation__to_node_9f7133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeedge",
            index=models.Index(fields=["mode"], name="navigation__mode_986498_idx"),
        ),
        migrations.AddConstraint(
            model_name="nodeedge",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_node", models.F("to_node")), _negated=True),
                name="nodeedge_no_self_loop",
            ),
        ),
        migrations.AddField(
            model_name="navigationsession",
            name="end_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ended_sessions",
                to="navigation.node",
            ),
        ),
        migrations.AddField(
            model_name="navigationsession",
            name="start_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_sessions",
                to="navigation.node",
            ),
        ),
        migrations.AddIndex(
            model_name="navigationsession",
            index=models.Index(
                fields=["created_at"], name="navigation__created_d0ad62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationsession",
            index=models.Index(
                fields=["preference_mode"], name="navigation__prefere_19e6dc_idx"
            ),
        ),
    ]
