# Generated by Django 6.0.1 on 2026-02-14 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0003_graphversion_navigationsession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="navigation_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="navigationsession",
            index=models.Index(
                fields=["start_node"], name="navigation__start_n_90c56a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationsession",
            index=models.Index(
                fields=["end_node"], name="navigation__end_nod_54bb17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationsession",
            index=models.Index(
                fields=["user", "created_at"], name="navigation__user_id_83406d_idx"
            ),
        ),
    ]
