# Generated by Django 6.0.1 on 2026-02-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0004_navigationsession_user_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="navigationsession",
            name="navigation__start_n_90c56a_idx",
        ),
        migrations.RemoveIndex(
            model_name="navigationsession",
            name="navigation__end_nod_54bb17_idx",
        ),
    ]
