# Generated by Django 6.0.1 on 2026-02-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0005_remove_navigationsession_navigation__start_n_90c56a_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSessionNodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.IntegerField()),
                ("is_connector", models.BooleanField(default=False)),
                ("hits", models.PositiveIntegerField(default=1)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_usage_rows",
                        to="navigation.node",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_usage_rows",
                        to="navigation.navigationsession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session"], name="navigation__session_786e84_idx"
                    ),
                    models.Index(
                        fields=["node"], name="navigation__node_id_1da2b2_idx"
                    ),
                    models.Index(fields=["floor"], name="navigation__floor_fc57d4_idx"),
                    models.Index(
                        fields=["is_connector"], name="navigation__is_conn_35648d_idx"
                    ),
                    models.Index(
                        fields=["session", "is_connector"],
                        name="navigation__session_cd1c54_idx",
                    ),
                ],
                "unique_together": {("session", "node")},
            },
        ),
    ]
