# Generated by Django 6.0.1 on 2026-02-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0006_navigationsessionnodeusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[
                    ("CLASSROOM", "Classroom"),
                    ("LAB", "Lab"),
                    ("AUDITORIUM", "Auditorium"),
                ],
                default="CLASSROOM",
                max_length=16,
            ),
        ),
    ]
