# Generated by Codex on 2026-02-26

from django.db import migrations


def backfill_room_type(apps, schema_editor):
    Room = apps.get_model("navigation", "Room")

    for room in Room.objects.all().iterator():
        normalized_name = (room.name or "").upper()

        if "LAB" in normalized_name:
            room_type = "LAB"
        elif "AUDITORIUM" in normalized_name or "HALL" in normalized_name:
            room_type = "AUDITORIUM"
        elif room.capacity and room.capacity >= 80:
            room_type = "AUDITORIUM"
        elif room.capacity and room.capacity <= 35:
            room_type = "LAB"
        else:
            room_type = "CLASSROOM"

        if room.type != room_type:
            room.type = room_type
            room.save(update_fields=["type"])


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0007_room_type"),
    ]

    operations = [
        migrations.RunPython(backfill_room_type, noop),
    ]

