# Generated by Django 6.0.1 on 2026-03-19 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0008_room_type_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "short_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampusNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("outdoor", "Outdoor"),
                            ("indoor", "Indoor"),
                            ("entry", "Entry"),
                            ("corridor", "Corridor"),
                            ("staircase", "Staircase"),
                        ],
                        default="outdoor",
                        max_length=16,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="navigation.campusbuilding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("floor", models.IntegerField(default=1)),
                ("capacity", models.IntegerField(default=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("occupied", "Occupied")],
                        default="available",
                        max_length=16,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="navigation.campusbuilding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampusEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField(default=0.0)),
                ("bidirectional", models.BooleanField(default=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_campus_edges",
                        to="navigation.campusnode",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_campus_edges",
                        to="navigation.campusnode",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_node", "to_node")},
            },
        ),
    ]
